name: test Odoo

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/sbidoul/oca-ci/py3.6-odoo13.0:latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('~/.cache/pip/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Addons and their dependencies
        run: oca_install_addons
      - name: Prepare test database
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
      - uses: codecov/codecov-action@v1
      - name: Export translations (.pot)
        run: |
          pip install click-odoo-contrib
          click-odoo-makepot -d odoo --msgmerge-if-new-pot --commit
          # TODO git push
      # TODO: OCB
