name: test Odoo

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest # TODO pin ubuntu version
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    env:
      ODOO_VERSION: "13.0"
      PGHOST: 127.0.0.1
      PGUSER: odoo
      PGPASSWORD: odoo
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('~/.cache/pip/wheels/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Odoo
        # TODO: run in the Odoo docker image with odoo and acsoo preinstalled?
        #       this could speedup install and avoid dependency
        #       on https://wheelhouse.acsone.eu/manylinux1
        run: |
          set -exo pipefail
          python3 -m venv odoo-venv
          export PIP_USE_FEATURE=2020-resolver
          odoo-venv/bin/pip install -U pip wheel setuptools
          git clone --depth=1 --branch=${ODOO_VERSION} https://github.com/odoo/odoo odoo-src
          odoo-venv/bin/pip install -r odoo-src/requirements.txt -e odoo-src -f https://wheelhouse.acsone.eu/manylinux1
          # websocket-client is needed for tour tests to not be skipped
          pip install -U websocket-client
      - name: Install acsoo (to get acsoo addons list and acsoo checklog commands)
        run: |
          set -exo pipefail
          python3 -m venv acsoo-venv
          export PIP_USE_FEATURE=2020-resolver
          acsoo-venv/bin/pip install -U pip wheel setuptools
          acsoo-venv/bin/pip install acsoo
      - name: Install Addons and their dependencies
        run: |
          set -exo pipefail
          SHORT_ODOO_VERSION=$(echo $ODOO_VERSION | cut -d '.' -f 1)
          touch test-requirements.txt
          for addon in $(ls setup/ -I README -I _metapackage) ; do
              addon_dist="odoo${SHORT_ODOO_VERSION}-addon-${addon}"
              echo "-e file://${PWD}/setup/${addon}#egg=${addon_dist}" >> test-requirements.txt
          done
          # use OCA wheelhouse because it is slightly fresher than PyPI
          odoo-venv/bin/pip install --pre -r test-requirements.txt \
            --extra-index-url https://wheelhouse.odoo-community.org/oca-simple/
      - name: Prepare test database
        run: |
          set -exo pipefail
          odoo-venv/bin/odoo -d odoo -i $(acsoo-venv/bin/acsoo addons list-depends) --stop-after-init
      - name: Run tests
        run: |
          set -exo pipefail
          odoo-venv/bin/odoo -d odoo -i $(acsoo-venv/bin/acsoo addons list) --test-enable --stop-after-init | acsoo-venv/bin/acsoo checklog
      # TODO: codecov
      # TODO: run click-odoo-makepot and push back to git repo if test success
      # TODO: support addon include/exclude mechanism
      # TODO: install wkhtmltopdf
      # TODO: install apt packages?
      # TODO: remove dependency on acsoo addons list
      # TODO: remove dependency on acsoo checklog
