name: test Odoo

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest # TODO pin ubuntu version
    container: quay.io/sbidoul/oca-ci:py36-odoo13
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    env:
      PGHOST: postgres
      PGUSER: odoo
      PGPASSWORD: odoo
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('~/.cache/pip/**') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Addons and their dependencies
        run: |
          set -ex
          touch test-requirements.txt
          for addon in $(ls setup/ -I README -I _metapackage) ; do
              echo "-e file://${PWD}/setup/${addon}#egg=odoo13-addon-${addon}" >> test-requirements.txt
          done
          # use OCA wheelhouse because it is slightly fresher than PyPI
          pip install --pre -r test-requirements.txt \
            --extra-index-url https://wheelhouse.odoo-community.org/oca-simple/
      - name: Prepare test database
        run: odoo -d odoo -i $(addons list-depends) --stop-after-init
      - name: Run tests
        run: coverage run $(which odoo) -d odoo -i $(addons list) --test-enable --stop-after-init
      - uses: codecov/codecov-action@v1
      - name: Export translations (.pot)
        run: |
           pip install click-odoo-contrib
           click-odoo-makepot -d odoo --msgmerge-if-new-pot --commit
           # TODO git push
      # TODO: support addon include/exclude mechanism
      # TODO: OCB
